import React from 'react';
import { withFocusable } from '@noriginmedia/react-spatial-navigation';

//  Creating this component to send listeners that apply to all the focusable items
//  Such as onBecameFocused, etc....
const FocusableItem = (props) => {
  //  Parsing props
  const {
    //  Props sent by parent
    children,
    className = '',
    tabIndex = 0,
    ref,
    onKeyDown, // In case we want to listen to tizen specific buttons
    style,
    itemId,
    //  Props generated by spatial navigation lib
    // setFocus,
    focused,
  } = props;

  //  Rendering
  return (
    <div
      id={itemId}
      className={`${className} ${focused ? 'focused' : ''}`}
      onKeyDown={onKeyDown}
      tabIndex={tabIndex}
      ref={ref}
      style={style}
    >
      {children}
    </div>
  );
};

export default withFocusable()(FocusableItem);
